name:                mhash
version:             0.1.0.0
github:              "Ryan-M3/mhash"
license:             CC0
author:              "Ryan McNamara"
maintainer:          "gn341ram@gmail.com"
copyright:           "2018 Ryan McNamara"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# To avoid duplicated efforts in documentation and dealing with the
# category:            Web

# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/mhash#readme>

dependencies:
- base           >= 4.7 && < 5
- HDBC           >= 2.4
- HDBC-sqlite3   >= 2.3
- directory      >= 1.3
- raw-strings-qq >= 1.0
- regex-base     >= 0.93
- regex-posix    >= 0.95
- regex-tdfa     >= 1.2
- parallel       >= 3.2
- criterion      >= 0.5

library:
  source-dirs: src

executables:
  mhash:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mhash

tests:
  mhash-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -g1 # disable parallel garbage collection
    - -qg0
    dependencies:
    - mhash
