name:                mhash
version:             0.1.0.0
github:              "githubuser/mhash"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/mhash#readme>

dependencies:
- base >= 4.7 && < 5
- HDBC >= 2.4
- HDBC-sqlite3 >= 2.3
- directory >= 1.3
- raw-strings-qq >= 1.0

library:
  source-dirs: src

executables:
  mhash:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mhash

tests:
  mhash-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mhash
